apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: k3d-local-registry:9090/app:latest
        imagePullPolicy: Always
        name: app
        env:
        - name: CONNECTION_STRING
          # value: root:password@tcp(mysql:3306)/defaultdb
          value: root:password@tcp(lms.lms.svc.cluster.local:9043)/defaultdb