{{- if .Values.orchestrator.tlsEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.orchestrator.tlsSecretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: orch-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.orchestrator.tlsSecretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ca.crt: '{{ printf "{{ .caCert }}" }}'
        tls.crt: '{{ printf "{{ .serverCert }}" }}'
        tls.key: '{{ printf "{{ .serverKey }}" }}'
  data:
  - secretKey: caCert
    remoteRef:
      key: orch-certs
      property: caCert
  - secretKey: serverCert
    remoteRef:
      key: orch-certs
      property: serverCert
  - secretKey: serverKey
    remoteRef:
      key: orch-certs
      property: serverKey
{{- end }}