# In order to initialize this secret store, follow the steps:
# Note the access key files are already gitignored by default.
# 1. echo -n 'KEYID' > ./access-key
# 2. echo -n 'SECRETKEY' > ./secret-access-key
# 3. kubectl create secret generic awssm-secret --from-file=./access-key --from-file=./secret-access-key
{{- if .Values.orchestrator.tlsEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: orch-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
{{- end }}