apiVersion: v1
kind: Secret
metadata:
  name: lms-secret
type: bootstrap.kubernetes.io/token
stringData:
  config.json: |
    {
      "INIT_SOURCE": "mysql://root:password@mysql.svc.cluster.local:3306/lms",
      "INIT_TARGET": "postgres://root@cockroachdb-public.crdb.svc.cluster.local:26257/lms?sslmode=disable"
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: orch-secret
type: bootstrap.kubernetes.io/token
stringData:
  config.json: |
    {
      "LMS_URL": "mysql://root:password@(molt-lms.default.svc.cluster.local:3306)/lms",
      "CRDB_URL": "postgresql://root@cockroachdb-public.crdb.svc.cluster.local:26257/lms?sslmode=disable"
    }