apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-internal
      port: 29092
      targetPort: 29092
    - name: kafka-external
      port: 9092
      targetPort: 9092
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: redpandadata/redpanda:latest
        args:
          - start
          - --smp 1
          - --overprovisioned
          - --node-id 0
          - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
          - --advertise-kafka-addr PLAINTEXT://kafka.default.svc.cluster.local:29092,OUTSIDE://localhost:9092
        ports:
        - containerPort: 29092
          name: kafka-internal
        - containerPort: 9092
          name: kafka-external