#  Copyright 2023 Cockroach Labs Inc.

#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at

#      http://www.apache.org/licenses/LICENSE-2.0

#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: v2
name: molt-lms
description: Helm chart for CRDB-Proxy

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.0.2"

icon: "https://upload.wikimedia.org/wikipedia/en/3/31/Cockroach_Labs_Logo.png"

dependencies:
- name: prometheus
  version: "22.6.6"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: deps.prometheus.enabled
- name: grafana
  version: "6.57.3"
  repository: "https://grafana.github.io/helm-charts"
  condition: deps.grafana.enabled
- name: loki
  version: "^5.9.2"
  repository: "https://grafana.github.io/helm-charts"
  condition: deps.loki.enabled
- name: promtail
  version: "6.14.1"
  repository: "https://grafana.github.io/helm-charts"
  condition: deps.promtail.enabled
- name: lms
  repository: https://molt.cockroachdb.com/lms/charts
  version: "0.0.0 - 1.0.0"
